import os
import datetime
import uuid

class MissionArchitect:
    def __init__(self, project_root):
        self.project_root = project_root
        self.template_path = os.path.join(project_root, "assets", "report_template.html")
        self.reports_dir = os.path.join(project_root, "reports")
        os.makedirs(self.reports_dir, exist_ok=True)

    def generate_report(self, squad_name, target_domain, mission_output):
        mission_id = str(uuid.uuid4())[:8].upper()
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # 1. Generate and save the Markdown report (Feynman style)
        md_content = f"# MISSION REPORT: {squad_name}\n"
        md_content += f"**ID:** {mission_id} | **Target:** {target_domain} | **Date:** {timestamp}\n\n"
        md_content += mission_output
        md_content += "\n\n---\n*Generated by TAMO Intelligence Squad*"

        md_filename = f"mission_{mission_id}.md"
        md_path = os.path.join(self.reports_dir, md_filename)
        with open(md_path, "w") as f:
            f.write(md_content)

        # 2. Prepare HTML content
        with open(self.template_path, "r") as f:
            template = f.read()

        # Better markdown to HTML conversion
        formatted_output = mission_output.replace("### ", "<h3>").replace("## ", "<h2>").replace("# ", "<h1>")
        formatted_output = formatted_output.replace("\n", "<br>")

        report_content = template.replace("{mission_id}", mission_id)
        report_content = report_content.replace("{timestamp}", timestamp)
        report_content = report_content.replace("{squad_name}", squad_name)
        report_content = report_content.replace("{target_domain}", target_domain)
        report_content = report_content.replace("{mission_output}", formatted_output)

        html_filename = f"mission_{mission_id}.html"
        html_path = os.path.join(self.reports_dir, html_filename)

        with open(html_path, "w") as f:
            f.write(report_content)

        return md_path, html_path
